fix: fix playwright not existing version error
See CI, all e2e tests are failing with

Error: browserType.launchPersistentContext: Executable doesn't exist at
/ms-playwright/chromium-1194/chrome-linux/chrome

╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to
1.56.1. ║
    ║ Please update docker image as well.
║
    ║ -  current: mcr.microsoft.com/playwright:v1.54.0-noble
║
    ║ - required: mcr.microsoft.com/playwright:v1.56.1-noble
║
    ║
║
    ║ <3 Playwright Team
║

╚══════════════════════════════════════════════════════════════════════╝