feat: visual editor (#1580)
* refactor: move markdown previewer to composer

* feat: add tiptap visual editor

* fix: share css between markdown and visual editor

* fix: sync visual editor content with model

* refactor: extract toolbar into dedicated component

* fix: handle image upload and links insertion

* fix: extract to composable, and handle images

* fix(ui): improve editor type switcher

* fix(perf): debounce the model update

fix: update model only when edited

* fix: convert the selection to markdown before copying

* refactor: better variable name

* feat: pasting markdown text should be interpreted

* feat: add syntax highlighting to code block

* fix: fix new leading new line when converting html to markdown

* fix: remove H1 from toolbar

* feat: allow node dragging

fix: remove extra div

fix: fix z-index

* fix(ui): add more spacing

* feat: use turndown to convert to markdown

refactore: use service directly

* tests: add tests for table conversion

* fix: add support for table header in tbody, and column alignment

* fix: add visual editor support for table alignment

* fix: add support for table without header

* feat: remove extra p inside list item

* fix(ux): show temp image while uploading

* fix: use definition placeholder when available

* fix(ui): update editor type switcher UI

* fix(ui): fix missing icon in toolbar

* fix: address copilot suggestion

* chore: remove unused dependencies

* fix: revert default editor to markdown

* fix: add dependencies

Those dependencies are not directly used, but necessary for @tiptap to
function, although not listed as dependency by it

* fix: nest css style

* refactor: improve type

* tests: remove redundant test

* fix: fix casing

* fix(ui): increase spacing

* fix: paste content as block only when necessary

* fix(ui): add highlight color on node selection

* fix: restraint the toolbar to the visual editor

* fix: do not restraint depth selection

* fix: remove drag

* feat: lazy load the visual editor

* fix: consider all markdown list as tight list

* fix(ui): remove H4 from toolbar

* fix: update classname for consistency

* fix: test with bottom toolbar

* fix(ui): fix toolbar overflowing screen width

* fix(ui): fix responsive issue

* fix(ui): define composer height once

* fix(ui): show loading indicator while loading async component

* fix: remember user's editor type in localstorage

* fix: regenerate yarn.lock after merge conflict

* fix: use camel case component name

* fix: fix the typescript issue

* refactor: migrate styles to tailwind classes

* refactor: improve type

* perf: improve accessibility

* refactor: use tailwind classes

* fix: remove incorrect event deregistration

* doc: add more comments about plugin function

* fix: fix deprecated Sass @import warning

* fix: clear the cdn url mapping cache on unmount

* fix: fix warning about non-props attrbutes

* fix: fix tiptap extension loaded multiple times

* fix: enable strikethrough in markdown parser

* fix: add strikethrough support to turndown

* fix: remove trim()

* fix: fix typescript error

tanstack/vue-query has been updated from 5.64.2 to 5.90.5, when
installing tiptap. The types has changes in this new version, and using
a array of unknown seems the recommend way:
https://tanstack.com/query/v5/docs/framework/vue/typescript#registering-the-query-and-mutation-key-types

* fix: fix playwright not existing version error

See CI, all e2e tests are failing with

Error: browserType.launchPersistentContext: Executable doesn't exist at
/ms-playwright/chromium-1194/chrome-linux/chrome

╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to
1.56.1. ║
    ║ Please update docker image as well.
║
    ║ -  current: mcr.microsoft.com/playwright:v1.54.0-noble
║
    ║ - required: mcr.microsoft.com/playwright:v1.56.1-noble
║
    ║
║
    ║ <3 Playwright Team
║

╚══════════════════════════════════════════════════════════════════════╝

* fix tests playwright version

* fix lint

---------

Co-authored-by: Chaitanya <yourchaitu@gmail.com>